Adding support for Syscoin
tomatoskittles/chains pull request #1
Opened 2021-08-27 15:59 UTC by tomatoskittles

2021-08-28 15:34 UTC, sidhujag requested changes

2021-08-28 15:34 UTC, sidhujag commented on _data/chains/eip155-5800.json
> +    "https://tanenbaum.io/api",
https://tanenbaum.io/api/eth-rpc, no ws

2021-08-28 15:34 UTC, sidhujag commented on _data/chains/eip155-57.json
> +    "https://tanenbaum.io/api",
https://nevm.syscoin.org/api/eth-rpc, no ws

2021-08-28 15:34 UTC, sidhujag commented on _data/chains/eip155-57.json
> +    "url": "https://tanenbaum.io",
nevm.syscoin.org not tanenbaum

2021-08-28 15:34 UTC, sidhujag commented on _data/chains/eip155-5800.json
> +    "standard": "EIP3091???"
it is not eip3091 compliant, dbl check this pls

2021-08-28 15:34 UTC, sidhujag commented on _data/chains/eip155-57.json
> +    "standard": "EIP3091???"
not eip3091 compliant, dbl check

2021-08-28 15:34 UTC, sidhujag commented on _data/chains/eip155-5800.json
> +  "faucets": ["https://faucet.tanenbaum.io"]
faucet.syscoin.org (not tanenbaum.io)

2021-08-28 15:34 UTC, sidhujag commented on _data/chains/eip155-5800.json
> +    "url": "https://syscoin.readme.io/",
tanenbaum.io not readme.io

2021-08-28 15:34 UTC, sidhujag commented on _data/chains/eip155-5800.json
> +  "network": "testnet",
tanenbaum not testnet

2021-08-28 15:34 UTC, sidhujag commented on _data/chains/eip155-5800.json
> +  "shortName": "sys",
tsys not sys

2021-08-28 15:38 UTC, sidhujag commented on _data/chains/eip155-5800.json
> +    "symbol": "SYS",
tSYS not SYS

2021-08-28 15:38 UTC, sidhujag commented on _data/chains/eip155-5800.json
> +    "name": "Syscoin",
Testnet Syscoin not Syscoin

2021-08-28 15:39 UTC, sidhujag commented on _data/chains/eip155-5800.json
> +}
infoURL missing?

2021-08-28 15:46 UTC, sidhujag commented on _data/chains/eip155-57.json
> +  "network": "mainnet",
Syscoin not mainnet

2021-08-30 19:33 UTC, sidhujag commented
looks good

2021-10-13 20:36 UTC, khai911013 commented
@ #

> 
Duplicate of #

2021-10-14 14:50 UTC, tomatoskittles commented
> @ #
> 
> > 
> 
> Duplicate of #

@khai911013 I'm not sure what this comment means... Can you elaborate? I want to delete this PR, as it is no longer needed. All of the changes have been merged to the upstream, via another branch and PR.

2021-12-10 16:54 UTC, closed without merging